[package]
name = "suanfa"
version = "0.1.0"
authors = ["lion <lion@olightworld.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
